-- MIGRATION 006 — Invoice Portal integration
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'PENDING_INVOICE_REVIEW';

ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS total_amount NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS outstanding_amount NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30),
  ADD COLUMN IF NOT EXISTS agreement_pdf_url TEXT;